default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: restaurants_nearby_development

test:
  <<: *default
  database: restaurants_nearby_test

production:
  <<: *default
  username: postgres
  host: db
  database: restaurants_nearby_production
  password: 
